const team = [
  { name: "Mehak Merai", role: "Team Lead & Full Stack Developer" },
  { name: "Anushka Phirke", role: "UI/UX Designer" },
  { name: "Kush Dudhe", role: "Backend & AI Logic" },
  { name: "Kalyani Khandve", role: "QA & Documentation" },
];

const techStack = ["HTML5", "CSS3", "JavaScript", "Tailwind CSS", "Node.js", "Express.js", "MongoDB", "JWT"];

function sectionHtml(icon, title, body) {
  return `
    <div class="card-glow p-6 animate-fade-in-up">
      <div class="flex items-center gap-2.5 mb-3">
        <i data-lucide="${icon}" class="w-5 h-5 text-primary"></i>
        <h3 class="font-semibold">${title}</h3>
      </div>
      <p class="text-sm text-muted leading-relaxed">${body}</p>
    </div>`;
}

export function render(root) {
  root.innerHTML = `
    <div class="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-14">
      <div class="text-center mb-12">
        <div class="eyebrow mb-4"><i data-lucide="graduation-cap" class="w-3.5 h-3.5"></i> Hackathon Project</div>
        <h1 class="font-display text-3xl font-normal tracking-tight">About CyberSure</h1>
        <p class="text-muted mt-3 max-w-2xl mx-auto">
          CyberSure was built by team Nexus to make digital security checks fast, free, and easy to understand for everyone.
        </p>
      </div>

      <div class="grid sm:grid-cols-2 gap-5 mb-10">
        ${sectionHtml(
          "target",
          "Our Mission",
          "Give anyone - not just security experts - a simple way to check whether a link, email, or message is trying to scam them, before they click, reply, or pay."
        )}
        ${sectionHtml(
          "eye",
          "Our Vision",
          "A web where scam checks are as normal as spell-check: quick, built into everyday browsing, and accessible to people of every age and technical background."
        )}
      </div>

      <div class="card p-6 mb-10">
        <div class="flex items-center gap-2.5 mb-4">
          <i data-lucide="cpu" class="w-5 h-5 text-primary"></i>
          <h3 class="font-semibold">Technology Used</h3>
        </div>
        <div class="flex flex-wrap gap-2">
          ${techStack
            .map(
              (t) => `<span class="text-xs font-mono font-medium bg-background border border-ink/15 rounded-full px-3 py-1.5 text-ink/70 hover:text-ink hover:border-ink/40 transition-colors">${t}</span>`
            )
            .join("")}
        </div>
        <p class="text-sm text-muted mt-4 leading-relaxed">
          Since this is a hackathon prototype, scan results are generated by rule-based logic that mimics how a trained AI model
          would score risk - looking for known scam signals like urgency language, suspicious domains, and brand impersonation.
        </p>
      </div>

      <div>
        <div class="flex items-center gap-2.5 mb-5 justify-center">
          <i data-lucide="users" class="w-5 h-5 text-primary"></i>
          <h3 class="font-semibold">Team Members</h3>
        </div>
        <div class="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">
          ${team
            .map(
              (m, i) => `
            <div class="card-glow p-5 text-center animate-fade-in-up" style="animation-delay:${i * 0.05}s">
              <div class="w-14 h-14 mx-auto rounded-full flex items-center justify-center font-bold mb-3 ring-2 ring-offset-2 ring-offset-card ${
                i % 2 === 0 ? "bg-primary/15 text-primary ring-primary/30" : "bg-accent/15 text-accent ring-accent/30"
              }">
                ${m.name.split(" ").map((n) => n[0]).join("")}
              </div>
              <div class="font-semibold text-sm">${m.name}</div>
              <div class="text-xs text-muted mt-0.5">${m.role}</div>
            </div>`
            )
            .join("")}
        </div>
      </div>
    </div>`;
}
